// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: non_constant_identifier_names, require_trailing_commas

part of 'closed_caption_track_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ClosedCaptionTrackInfoImpl _$$ClosedCaptionTrackInfoImplFromJson(
        Map<String, dynamic> json) =>
    _$ClosedCaptionTrackInfoImpl(
      Uri.parse(json['url'] as String),
      Language.fromJson(json['language'] as Map<String, dynamic>),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      format:
          ClosedCaptionFormat.fromJson(json['format'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$ClosedCaptionTrackInfoImplToJson(
        _$ClosedCaptionTrackInfoImpl instance) =>
    <String, dynamic>{
      'url': instance.url.toString(),
      'language': instance.language,
      'isAutoGenerated': instance.isAutoGenerated,
      'format': instance.format,
    };
